### PR TITLE
get_table function and tests

### PR DESCRIPTION
**Pull request by FloatingBrioche**

### CODE REVIEW

**Comment by dkettchen** [comment]
In test file: 
-please make sure to refactor util placeholders using the actual utils as imports once they're approved & available on main
-why are you using side effect for your mock rather than return value? 

Overall: no problems I can see with the code, seems correct. :)

**Comment by FloatingBrioche** [comment]
Cheers! I used a side effect just because it seemed like a slightly fuller mocking of the conn.run() invocation and process of querying  the data.

**Comment by dkettchen** [comment]
In what sense? Aren't we just looking for the return value of "connection.run"ning the query?

**Review by dkettchen — APPROVED** [review]
Looking good for now, additional refactoring can be done & reviewed later :)

**Pull request merged**
